server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-order?reWriteBatchedInserts=true
    username: ${MS_PG_USER:monty}
    password: ${MS_PG_PWD:monty}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        generate_statistics: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:io.github.montytsai.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    product-url: http://localhost:8050/api/v1/product
