package io.github.montytsai.ecommerce.customer;

import org.mapstruct.*;

@Mapper(componentModel = "spring", uses = CustomerCheckUtils.class)
public interface CustomerMapper {

    // for POST / PUT, ignore id since it will be generated by the database
    @Mapping(target = "id", ignore = true)
    Customer toCustomer(CustomerRequest request);

    Address toAddress(AddressRequest request);

    // for PATCH, ignore null/blank values to prevent overwriting existing values with blank
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void patchCustomer(CustomerRequest request, @MappingTarget Customer customer);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void patchAddress(AddressRequest request, @MappingTarget Address address);

    CustomerResponse fromCustomer(Customer customer);

    AddressResponse fromAddress(Address address);

}
