services:
  # ===== Core Databases =====
  # --- PostgreSQL ---
  postgres:
    container_name: ms-pg-sql
    image: postgres
    environment:
      POSTGRES_USER: ${MS_PG_USER:-monty}
      POSTGRES_PASSWORD: ${MS_PG_PWD:-monty}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  # --- MongoDB ---
  mongo:
    container_name: ms-mongo-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: customer
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-monty}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-monty}
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - microservices-net
    restart: unless-stopped

  # ===== Database UI Tools =====
  # --- pgAdmin ---
  pgadmin:
    container_name: ms-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  # --- Mongo-Express ---
  mongo-express:
    container_name: ms-mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=monty
      - ME_CONFIG_MONGODB_ADMINPASSWORD=monty
    ports:
      - 8082:8081
    networks:
      - microservices-net
    depends_on:
      - mongo
    restart: unless-stopped

  # ===== Utility Services =====
  # --- MailDev ---
  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

# ===== Infrastructure Persistence Definitions =====
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  pgadmin_data:
